import * as monaco from 'monaco-editor';

export function defineMonacoThemes() {
    monaco.editor.defineTheme('sourcepad-dark', {
        base: 'vs-dark',
        inherit: true,
        rules: [
            { token: 'comment', foreground: '6e7681', fontStyle: 'italic' },
            { token: 'keyword', foreground: 'ff7b72', fontStyle: 'bold' },
            { token: 'string', foreground: 'a5d6ff' },
            { token: 'number', foreground: '79c0ff' },
            { token: 'regexp', foreground: '7ee787' },
            { token: 'operator', foreground: 'ff7b72' },
            { token: 'namespace', foreground: 'ffa657' },
            { token: 'type', foreground: 'ffa657' },
            { token: 'struct', foreground: 'ffa657' },
            { token: 'class', foreground: 'ffa657' },
            { token: 'interface', foreground: 'ffa657' },
            { token: 'parameter', foreground: 'ffa657' },
            { token: 'variable', foreground: 'f0f6fc' },
            { token: 'variable.predefined', foreground: 'f0f6fc' },
            { token: 'constant', foreground: 'ffa657' },
            { token: 'function', foreground: 'd2a8ff' },
            { token: 'member', foreground: 'd2a8ff' },
            { token: 'tag', foreground: '7ee787' },
            { token: 'attribute.name', foreground: '79c0ff' },
            { token: 'attribute.value', foreground: 'a5d6ff' },
            { token: 'delimiter.html', foreground: '8b949e' },
            { token: 'delimiter.xml', foreground: '8b949e' },
        ],
        colors: {
            'editor.background': '#0d1117',
            'editor.foreground': '#f0f6fc',
            'editorLineNumber.foreground': '#6e7681',
            'editorLineNumber.activeForeground': '#f0f6fc',
            'editor.selectionBackground': '#264f78',
            'editor.inactiveSelectionBackground': '#3a3d41',
            'editor.lineHighlightBackground': '#161b22',
            'editorCursor.foreground': '#f0f6fc',
            'editorWhitespace.foreground': '#484f58',
            'editorIndentGuide.background': '#21262d',
            'editorIndentGuide.activeBackground': '#30363d',
            'editorBracketMatch.background': '#3d424a',
            'editorBracketMatch.border': '#58a6ff',
            'editorError.foreground': '#f85149',
            'editorWarning.foreground': '#d29922',
            'editorInfo.foreground': '#58a6ff',
            'editorHint.foreground': '#8b949e',
            'editorGutter.background': '#0d1117',
            'editorGutter.modifiedBackground': '#d29922',
            'editorGutter.addedBackground': '#238636',
            'editorGutter.deletedBackground': '#da3633',
            'scrollbarSlider.background': '#6e7681',
            'scrollbarSlider.hoverBackground': '#8b949e',
            'scrollbarSlider.activeBackground': '#f0f6fc'
        }
    });

    monaco.editor.defineTheme('sourcepad-light', {
        base: 'vs',
        inherit: true,
        rules: [
            { token: 'comment', foreground: '8c959f', fontStyle: 'italic' },
            { token: 'keyword', foreground: 'cf222e', fontStyle: 'bold' },
            { token: 'string', foreground: '0969da' },
            { token: 'number', foreground: '0550ae' },
            { token: 'regexp', foreground: '1a7f37' },
            { token: 'operator', foreground: 'cf222e' },
            { token: 'namespace', foreground: '953800' },
            { token: 'type', foreground: '953800' },
            { token: 'struct', foreground: '953800' },
            { token: 'class', foreground: '953800' },
            { token: 'interface', foreground: '953800' },
            { token: 'parameter', foreground: '953800' },
            { token: 'variable', foreground: '24292f' },
            { token: 'variable.predefined', foreground: '24292f' },
            { token: 'constant', foreground: '953800' },
            { token: 'function', foreground: '8250df' },
            { token: 'member', foreground: '8250df' },
            { token: 'tag', foreground: '1a7f37' },
            { token: 'attribute.name', foreground: '0550ae' },
            { token: 'attribute.value', foreground: '0969da' },
            { token: 'delimiter.html', foreground: '656d76' },
            { token: 'delimiter.xml', foreground: '656d76' },
        ],
        colors: {
            'editor.background': '#ffffff',
            'editor.foreground': '#24292f',
            'editorLineNumber.foreground': '#8c959f',
            'editorLineNumber.activeForeground': '#24292f',
            'editor.selectionBackground': '#b6d7ff',
            'editor.inactiveSelectionBackground': '#e7e9eb',
            'editor.lineHighlightBackground': '#f6f8fa',
            'editorCursor.foreground': '#24292f',
            'editorWhitespace.foreground': '#8c959f',
            'editorIndentGuide.background': '#d0d7de',
            'editorIndentGuide.activeBackground': '#8c959f',
            'editorBracketMatch.background': '#ddf4ff',
            'editorBracketMatch.border': '#0969da',
            'editorError.foreground': '#cf222e',
            'editorWarning.foreground': '#9a6700',
            'editorInfo.foreground': '#0969da',
            'editorHint.foreground': '#656d76',
            'editorGutter.background': '#ffffff',
            'editorGutter.modifiedBackground': '#9a6700',
            'editorGutter.addedBackground': '#1a7f37',
            'editorGutter.deletedBackground': '#cf222e',
            'scrollbarSlider.background': '#8c959f',
            'scrollbarSlider.hoverBackground': '#656d76',
            'scrollbarSlider.activeBackground': '#24292f'
        }
    });
}
